const express = require('express')
const env = require("dotenv")
const db = require('./config/db')
const cors = require('cors')
env.config({path:"./config//.env"})
const user = require("./routes/user-router")
db()
const app = express()
app.use(express.json())
app.use(cors())
app.use("/api/user",user)
app.listen(process.env.PORT, () => console.log(`Example app listening on port ${process.env.PORT}`))